version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql_jwt
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql_jwt
      MYSQL_USER: seung
      MYSQL_PASSWORD: 1234


# docker-compose -f docker-compose-mysql.yml up -d
# docker-compose -f docker-compose-redis.yml -f docker-compose-mysql.yml up -d
